// levels.js — Level definitions
(function () {
  const LEVELS = [
    {
      id: 1,
      name: 'Forest Hunt',
      bnName: 'বনে শিকার',
      icon: '🦌',
      vehicle: 'foot',
      biome: 'forest',
      worldW: 1800,
      worldH: 1800,
      target: 8,                 // animals to kill
      objective: 'kill',         // 'kill' | 'loot'
      spawn: { rabbit: 6, deer: 5, boar: 2 },
      decorations: { trees: 50, bushes: 25, rocks: 12 },
      ammoStart: 30,
      timeLimit: 120,
    },
    {
      id: 2,
      name: 'Bike Hunt',
      bnName: 'বাইকে শিকার',
      icon: '🏍️',
      vehicle: 'bike',
      biome: 'forest',
      worldW: 2400,
      worldH: 2400,
      target: 12,
      objective: 'kill',
      spawn: { rabbit: 8, deer: 7, boar: 5 },
      decorations: { trees: 70, bushes: 40, rocks: 18 },
      ammoStart: 35,
      timeLimit: 150,
    },
    {
      id: 3,
      name: 'River Hunt',
      bnName: 'নদীর শিকার',
      icon: '🛶',
      vehicle: 'boat',
      biome: 'river',
      worldW: 2400,
      worldH: 2400,
      target: 12,
      objective: 'kill',
      spawn: { duck: 10, crocodile: 6 },
      decorations: { rocks: 8 },
      ammoStart: 40,
      timeLimit: 150,
    },
    {
      id: 4,
      name: 'Deep Jungle',
      bnName: 'গহিন জঙ্গল',
      icon: '🐅',
      vehicle: 'car',
      biome: 'forest',
      worldW: 2800,
      worldH: 2800,
      target: 10,
      objective: 'kill',
      spawn: { boar: 4, tiger: 4, bear: 4 },
      decorations: { trees: 100, bushes: 50, rocks: 25 },
      ammoStart: 50,
      timeLimit: 180,
    },
    {
      id: 5,
      name: 'Village Raid',
      bnName: 'গ্রামে হানা',
      icon: '🏚️',
      vehicle: 'foot',
      biome: 'village',
      worldW: 2200,
      worldH: 2200,
      target: 6,                 // houses to loot
      objective: 'loot',
      spawn: { villager: 8 },
      houses: 6,
      crates: 12,
      decorations: { trees: 12, bushes: 8 },
      ammoStart: 45,
      timeLimit: 180,
    },
  ];

  window.LEVELS = LEVELS;
})();
